service: nodeless

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-east-1
  # 256 mb
  memorySize: 256
  # Quais servicos está autorizado a utilizar
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource:
        - "arn:aws:s3:::*"

functions:
  optimize:
    handler: optimize.handle
    environment:
      bucket: rocketserverlessnodejs2
    events:
      - s3:
          bucket: rocketserverlessnodejs2
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .jpg
      - s3:
          bucket: rocketserverlessnodejs2
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .png
            